### ISSUE TITLE
Ext.Toolkits: PieChart evaluieren 

### ISSUE THREAD

**Issue by sebastian-steindl** [AlexOth/swp-ss19#23]
Für Statistik anzeigen, Zeitaufwand nach Gebiet als PieChart

**Comment by AlexOth** [comment]
Würde schon was hermachen.

`PieChart` ist aber nur *ein* Segment davon. Also müsste man ein Diagramm implementieren, dass aus mehreren PieCharts das ganze manuell zusammenbaut.
