### ISSUE TITLE
Ext.Toolkits: RichTextBoxFormatBar evaluieren

### ISSUE THREAD

**Issue by sebastian-steindl** [AlexOth/swp-ss19#27]
In Kombination mit RichTextBox für Beschreibungen

**Comment by AlexOth** [comment]
MMn Eher schwierig, da wir Beschreibungen und alles als `string` im Model und der Datenbank haben.
Zumindest wüsste ich nicht auf anhieb, wie man die Text-Formatierung dann im Model unterbringt.
