### ISSUE TITLE
Statistik erstellen Filedialog geht nicht

### ISSUE THREAD

**Issue by LMoeges** [AlexOth/swp-ss19#35]
(mehr?)

**Comment by mwagneroth** [comment]
gehörte nie zu meinen Aufgaben.
Ich hab nur die Export-Klasse geschrieben, aber der File-Dialog ist Angelegenheit des Aufrufers meiner Klasse.

**Comment by LMoeges** [comment]
Aber jetzt ist das deine Aufgabe

**Comment by mwagneroth** [comment]
Moved to other Tab (Zeitprotokoll exportieren) and does work there.
