### ISSUE TITLE
Add null-checks to model class-constructors

### ISSUE THREAD

**Issue by mwagneroth** [AlexOth/swp-ss19#39]
Add null-checks to model class constructors to prevent System.NullReferenceExceptions in Datenbankmodell.Save()-classes.
Add null-check for every variable, which are given to the constructor, to make sure, that every object is initialized correctly.
E.g.:
void Object(string str, int numb)
{
        if(str.IsNullOrEmpty() || numb == null) throw new ArgumentException("An argument is NULL!");
}

**Comment by LMoeges** [comment]
Müsste bereits erledigt sein, oder?
Wenn ja bitte Issue schließen.
